### ISSUE TITLE
Using Angara.Html with Json.NET 9.x

### ISSUE THREAD

**Issue by cgravill** [Microsoft/Angara#2]
### Description

I'd like to use Angara.Html with in an F# Jupyter Notebook fsprojects/IfSharp using Json.NET 9.0.1
### Actual behavior

Angara.Html 0.2.4 has a strict upper bound on this:
Newtonsoft.Json (>= 8.0.0 && < 9.0.0) 

Are there any known issues with supporting newer versions?
### Known workarounds

Rebuild myself, but that doesn't allow users of the notebook to acquire it.

**Comment by dvoits** [comment]
There should be no problem to support new version of Newtonsoft.Json.
I'm updating it and also moving Angara.Html to the just released IDD.

**Comment by dvoits** [comment]
Actually the strict bounds were used because the NewtonsoftJson's assembly file name was changed and it caused issues.

**Comment by dvoits** [comment]
Done. Angara.Html 0.2.5 uses Newtonsft.Json 9.0.1 and IDD 1.4.2 which allows to download svg using UI button.

**Comment by cgravill** [comment]
Thanks, that sounds ideal!
